### ISSUE TITLE
Lightbox Not Center When in Mobile View (Responsive)

### ISSUE THREAD

**Issue by riyantowibowo** [frontend-collective/react-image-lightbox#91] opened 2017-11-28 11:15 UTC
I don't have any clue why when Lightbox opened in mobile view it doesn't appear in the center of screen.

![screen shot 2017-11-28 at 18 01 24](https://user-images.githubusercontent.com/7629714/33316874-14d7d18a-d468-11e7-8004-88d00dd85b50.png)

But for desktop view and demo, it seem okay.

I think it has an issue in css transform.
So for temporary solution I just put css transform:none, yes that will make the lightbox to center
But I can't drag or zoom with css transform:none

**Comment by fritz-c** [comment] 2017-11-28 11:23
Can you reproduce this in a fork of this example? https://codesandbox.io/s/wkw2mjm5l8

**Comment by iyasayariyan** [comment] 2017-11-29 07:48
hi @fritz-c unfortunately I can't replicate in this fork https://codesandbox.io/s/yp2jlmno9
I am pretty sure my code just like that, I just put one image in lightbox and little bit modify css, that's all what I did

**Comment by fritz-c** [comment] 2017-11-29 07:50
Can you give me some details about what kind of modifications you made in the css? There's a decent chance something got inherited inside the lightbox.

**Comment by iyasayariyan** [comment] 2017-11-29 07:59
I customise css for design implementation purpose
- custom loading animation
- custom close button
- hide zoom in/out buttons

`
.ReactModal__Body--open{
	.ril__loadingContainer__icon{
		background: url(/assets/images/rolling.gif);
		background-size: contain;
		*{
			display: none
		}
	}
	.ril__outer{
		background-color: rgba(0, 0, 0, 0.8);
	}
	.ril__toolbar{
		background-color: transparent;
	}
	.ril-toolbar-right .ril__toolbarItem{
		display: none;
		background-color: $c-black;
		border-radius: 100%;
		width: 50px;
		height: 50px;
		text-align: center;
		line-height: 2.3em;
		margin-top: 20px;
		@media only screen and (max-width: 1023px){
			width: 40px;
			height: 40px;
			line-height: 1.8em;
		}
		&:last-child{
			display: inline-block;
		}
	}
	.ril__image{
		@media only screen and (max-width: 1023px){
			transform: none !important;
		}
	}
}
`

**Comment by nidhi-tandon** [comment] 2018-01-03 09:29
@iyasayariyan Hey...Have you solved this issue? I am getting the same issue in my project.

**Comment by fritz-c** [comment] 2018-01-14 00:48
@iyasayariyan Is this still broken for you in the latest version? I think it might be due to a default `max-width` style in some frameworks that I have since merged in a fix (#73) for. I'm basing this off of [this comment](https://github.com/fritz-c/react-image-lightbox/issues/93#issuecomment-353072377).

**Comment by l29ah** [comment] 2018-02-10 18:39
![](https://a.pomfe.co/qeltht.png)

Got this on palemoon from git, but works ok on firefox-esr.

**Comment by vekerdyb** [comment] 2018-03-07 16:06
I see a similar issue, but only with portrait images only on iOS. (Chrome, Safari.)

Sometime the image is not visible at all, and when pressing zoom it becomes visible.

I wasn't able to reproduce on any other device / screen size.

I will provide more info when I get home -- I don't have my iPhone cable to debug on me.

**Comment by AonanLi** [comment] 2018-04-25 18:07
It still happens on my phone, even after the max-width fix. It only happens to portrait taken images. 
On my pc it doesn's show the correct image orientation, but the size and center is ok.
On iOS it shows the orientation correctly, but the center is far away from the screen.
I'm assuming there is a process changing image orientation based on the orientation data stored in the photo, and this process doesn't handle the image width or height correctly, which leads to a wrong calculation to the css transform coordinates.

**Comment by OPY-bbt** [comment] 2018-06-06 07:12
Have you solved this issue? I am getting the same issue in my project. but only in IOS

**Comment by OPY-bbt** [comment] 2018-06-08 01:43
I have solved this in IOS. npm install @zhyabs1314/react-image-lightbox

**Comment by mattiascibien** [comment] 2018-06-20 15:22
I have the same problem at http://next.mattiascibien.net/gallery (try to shrink the browser window and click on the button for opening an image)

**Comment by sami616** [comment] 2018-11-09 06:37
Seeing this too sadly.

**Comment by yuzhakovvv** [comment] 2019-03-13 10:20
Same here. Happens in WebView on iOS

**Comment by kaYcee** [comment] 2019-06-20 05:23
Seeing this too. Seems to affect especially images with a specific EXIF orientation that Safari on iOS auto-rotates.

**Comment by BrunildaNinox** [comment] 2019-08-15 12:09
have you guys solved this?

**Comment by OPY-bbt** [comment] 2019-08-16 02:23
#122

**Comment by maxim-pushchinskiy** [comment] 2019-09-17 12:10
have the same issue. I even can reproduce it on desktop, if width of my browser window will be less than width of image. I guess the reason of this behavior in `getTransform` method. I don't understand for which case we need this code: 
`if (width > windowWidth) {
      nextX += (width - windowWidth) / 2;
  }`
But if we remove it, everything works fine, except animation.

**Comment by maxim-pushchinskiy** [comment] 2019-10-09 10:30
if someone try to find solution: you can or remove `discourageDownloads` flag or https://github.com/frontend-collective/react-image-lightbox/pull/193

**Comment by samvk** [comment] 2020-02-13 20:46
I was able to fix this issue for me by setting `max-width: none;` _and_ `max-height: none;` on ril images.

**Comment by stevomcnevo** [comment] 2020-03-03 15:54
Add this to styles:


.ril-image-current {
    max-width: none !important;
}

**Comment by saravanan0701** [comment] 2021-03-15 04:40
.ril-image-current {
    transform: none !important;
}

this helped me solve the issue

**Comment by pritam693** [comment] 2021-07-15 11:57
This solves the issue but disables the zoom feature 

> .ril-image-current {
> transform: none !important;
> }
> 
> this helped me solve the issue

but this disables the zoom feature

**Closed** 2023-01-19 15:12 UTC
Labels: bug
