### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

### ISSUE THREAD

**Issue by constantinpojoga** [frontend-collective/react-image-lightbox#187] opened 2019-08-30 15:24 UTC
Hi, thank you for the great tool!
Wanted to ask if you can fix this issue: in Chrome I'm getting thousands of these messages, [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See See https://www.chromestatus.com/features/6662647093133312

Thank you

**Comment by dylangrandmont** [comment] 2019-09-30 14:47
Looks like a duplicate of a fixed issue https://github.com/frontend-collective/react-image-lightbox/issues/171. **However** that fix has not been published yet.

I ran into this issue as well today on the latest `npm` package. Are there plans to cut a release with this fix in it?

**Comment by Paulus90** [comment] 2019-10-08 09:44
Will this be fixed anytime soon? Errors are piling up in Chrome...

**Comment by online0227** [comment] 2019-11-09 16:36
Is this fixed? I still get the error

**Comment by smenshikov** [comment] 2021-01-05 19:02
Today is 2021! I still get the error

**Comment by AidenBurgess** [comment] 2021-07-02 03:16
Still getting error

**Comment by liuhe2020** [comment] 2021-10-07 00:48
Still getting error

**Comment by JoniRinta-Kahila** [comment] 2022-01-08 17:18
Same error will continue in 2022!

**Comment by Jay-WKJun** [comment] 2022-05-06 00:42
Still get same Errors in 2022!

**Closed** 2023-01-19 15:12 UTC
