### ISSUE TITLE
ReactImageLightbox Not working in latest React version  -  react  16.9.0 

### ISSUE THREAD

**Issue by nataliaroque77** [frontend-collective/react-image-lightbox#303] opened 2020-04-29 08:08 UTC
# Reporting a Bug?

Please update the following components: ReactImageLightbox
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-image-lightbox": "^5.1.1",
    "typescript": "^3.6.2"

**Comment by Slapbox** [comment] 2020-05-06 00:40
That's not a bug - it's only a warning.

**Comment by a1xter** [comment] 2020-12-05 07:33
I have the same issue. And yep it is not an error but it's annoying. Is it possible to fix it?

**Comment by ostefani** [comment] 2020-12-11 10:06
Is it planned to support React 17?

**Comment by browniebroke** [comment] 2021-07-13 10:02
I think the warning should be gone in [version 5.1.2](https://github.com/frontend-collective/react-image-lightbox/compare/v5.1.1...v5.1.2) and later.

**Comment by fritz-c** [comment] 2021-07-13 23:02
Should be fixed now. Thank you.

**Closed by fritz-c** 2021-07-13 23:02 UTC
